language: python
python:
    - "2.7"

install:
  - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
        python setup.py develop --no-deps;
      else
        pip install -r requirements.txt
        python setup.py develop --no-deps;
      fi'
  - pip install -r test_requirements.txt
  - pip install -r docs_requirements.txt

script:
    - nosetests --with-coverage --cover-package=autodiscovery tests
    - sphinx-build -c docs/ -nW -b latex -d docs/_build/doctrees docs docs/_build/pdf
    - cd docs/_build/pdf && latex cloudshell-autodiscovery
#    - python setup.py bdist_egg --exclude-source-files

after_success:
    - coveralls
