VENDOR_ENTERPRISE_NUMBERS_URL = "https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers"
DATA_FOLDER = "data"
EXAMPLES_FOLDER = "examples"
VENDOR_ENTERPRISE_NUMBERS_FILE = "vendor_enterprise_numbers.json"
VENDORS_CONFIG_FILE = "vendors_config.json"
VENDORS_CONFIG_EXAMPLE_FILE = "vendors_config_example.json"
USER_INPUT_EXAMPLE_FILE = "user_input_example.yml"
DEFAULT_CLOUDSHELL_DOMAIN = "Global"
DEFAULT_RESOURCE_FOLDER_PATH = ""  # root folder
